### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by mnvwvnm** [akaalias/getquickdown#1]
Hi.
I found your new project: a great fast menu-bar note-taking to complement with Obsidian.
But... It seems only available for macOS v12.
There's any chance to allow lower macos versions?
Thank you.

**Comment by akaalias** [comment]
Hey there! Thank you for posting, that's a good question – I'll look into it and get back to you.

**Comment by akaalias** [comment]
Hey! 

Just checked and a bunch of APIs I'm using are minimum 12.0. So, for now the compatibility will be macOS 12 or higher. 

However, as the code is open-source, you could create a branch and see if you can retro-fit it yourself!

Here some example incompatibilities with macOS 11.5: 

<img width="576" alt="Screenshot 2022-01-24 at 10 14 46" src="https://user-images.githubusercontent.com/111555/150764243-fd4dcfd8-bb7e-427b-bef2-7722e92714b3.png">
